name: Scheduled Test

on:
  schedule:
    - cron: '* * * * *'  # Every minute

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Test Scheduled Job
        run: echo "Scheduled job is running!"

