name: Nightly tests

on:
  schedule:
    - cron: '15 23 * * *'
  workflow_dispatch:

jobs:
  nightly_job_default:
    if: github.repository_owner == 'input-output-hk'
    # reusable workflow from local repo and same branch as this config
    uses: ./.github/workflows/regression_reusable.yaml
    with:
      env-path: .github/env_nightly
    secrets:
      CI_FAIL_MAILS: ${{ secrets.NIGHTLY_FAIL_MAILS }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
