# ./.tmuxinator.yml

name: preview
root: /home/artur/Playground/blockchain_networks/Base_Projects

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false


windows:
    - editor:
            layout: tiled
            panes:
              - node:
                - if [ -d "cardano-node" ]; then echo "Repository already exists."; else git clone https://github.com/input-output-hk/cardano-node; fi
                - cd cardano-node
                #- git checkout master
                #- git pull origin master
                #- git fetch --all --tags
                #- git checkout tags/1.35.3
                - if [ -d "preview" ]; then echo "Preview Config folder already exists."; else cp -R /home/artur/Playground/blockchain_networks/preview/preview . ; fi
                - ./_cardano-node run --topology preview/topology.json --database-path preview/db --socket-path preview/node.socket --config preview/config.json


              - db-sync:
                - if [ -d "cardano-db-sync" ]; then echo "Repository already exists."; else git clone https://github.com/input-output-hk/cardano-db-sync; fi
                - cd cardano-db-sync
                #- git checkout master
                #- git pull origin master
                #- git fetch --all --tags
                #- git checkout tags/13.0.5
                #- nix-build -A cardano-db-sync -o db-sync-node
                #- psql -c "DROP DATABASE preview_playground"
                #- PGPASSFILE=config/pgpass-preview scripts/postgresql-setup.sh --createdb
                - PGPASSFILE=config/pgpass-preview db-sync-node/bin/cardano-db-sync --config config/preview-config.yaml --socket-path ../cardano-node/preview/node.socket --schema-dir schema/ --state-dir ledger-state/preview


              - smash:
                - cd cardano-db-sync
                #- cabal build cardano-smash-server
                #- cp $(find . -name cardano-smash-server -executable -type f) /home/artur/Playground/blockchain_networks/Base_Projects/cardano-db-sync/_cardano-smash-server
                #- echo "artur, password" > admins.txt
                - PGPASSFILE=config/pgpass-preview ./_cardano-smash-server --config config/preview-config.yaml --port 3100 --admins admins.txt


              - node_playground:
                - sleep 20
                - export CARDANO_NODE_SOCKET_PATH=/home/artur/Playground/blockchain_networks/Base_Projects/cardano-node/preview/node.socket
                - cardano-cli query tip --testnet-magic 2


              - smash_playground:
                - sleep 20
                - cat /home/artur/Playground/blockchain_networks/preview/preview.txt
                - echo "Checking SMASH service status:"
                - curl http://localhost:3100/api/v1/status
